export const teachers = [{"id":1, "name":"A G Sharma", "subject":"Biology", "phone": "","location":"","service_year":"" ,"invitation_sent":false},
{"id":2, "name":"A Rahman", "subject":"PET", "phone": "","location":"","service_year":"" ,"invitation_sent":false},
{"id":3, "name":"Anwar hussain", "subject":"Chemistry", "phone": "","location":"","service_year":"" ,"invitation_sent":false},
{"id":4, "name":"Archana Maam", "subject":"Computer", "phone": "","location":"","service_year":"" ,"invitation_sent":false},
{"id":5, "name":"Arvind Kumar", "subject":"Geography", "phone": "","location":"","service_year":"" ,"invitation_sent":false},
{"id":6, "name":"Ashutosh sir.", "subject":"Maths", "phone": "","location":"","service_year":"" ,"invitation_sent":false},
{"id":7, "name":"Ashwini Kumar Mahanta", "subject":"PET", "phone": "","location":"","service_year":"" ,"invitation_sent":false},
{"id":8, "name":"Barman Khura", "subject":"Mess", "phone": "","location":"","service_year":"" ,"invitation_sent":false},
{"id":9, "name":"Bhowmik", "subject":"Library", "phone": "","location":"","service_year":"" ,"invitation_sent":false},
{"id":10, "name":"Bhup Singh", "subject":"Geography", "phone": "","location":"","service_year":"" ,"invitation_sent":false},
{"id":11, "name":"Bijoy Pratap yadav", "subject":"Hindi", "phone": "","location":"","service_year":"" ,"invitation_sent":false},
{"id":12, "name":"Bimal Sharma", "subject":"Assamese", "phone": "","location":"","service_year":"" ,"invitation_sent":false},
{"id":13, "name":"Biplab Das", "subject":"HM", "phone": "","location":"","service_year":"" ,"invitation_sent":false},
{"id":14, "name":"Bipul Sinha", "subject":"Chemistry", "phone": "","location":"","service_year":"" ,"invitation_sent":false},
{"id":15, "name":"Bishwa mohan prashad", "subject":"Science", "phone": "","location":"","service_year":"" ,"invitation_sent":false},
{"id":16, "name":"BM Prasad", "subject":"Science", "phone": "","location":"","service_year":"" ,"invitation_sent":false},
{"id":17, "name":"Choubey Sir.", "subject":"History", "phone": "","location":"","service_year":"" ,"invitation_sent":false},
{"id":18, "name":"D D Das", "subject":"Hindi", "phone": "","location":"","service_year":"" ,"invitation_sent":false},
{"id":19, "name":"DC Pathak", "subject":"Principal", "phone": "","location":"","service_year":"" ,"invitation_sent":false},
{"id":20, "name":"Dhritri Deka", "subject":"Hindi", "phone": "","location":"JNV Rangiya","service_year":"" ,"invitation_sent":false},
{"id":21, "name":"Faruk Da", "subject":"Driver", "phone": "","location":"","service_year":"" ,"invitation_sent":false},
{"id":22, "name":"G Giridhar", "subject":"Science", "phone": "","location":"","service_year":"" ,"invitation_sent":false},
{"id":23, "name":"G.S. Meena", "subject":"Principal", "phone": "","location":"","service_year":"" ,"invitation_sent":false},
{"id":24, "name":"Gaikwad", "subject":"Maths", "phone": "","location":"","service_year":"" ,"invitation_sent":false},
{"id":25, "name":"Ganesh Deka", "subject":"Assamese", "phone": "7002019938","location":"","service_year":"" ,"invitation_sent":false},
{"id":26, "name":"Ganesh Sankar", "subject":"English", "phone": "","location":"","service_year":"" ,"invitation_sent":false},
{"id":27, "name":"Girish Deka", "subject":"Assamese", "phone": "","location":"","service_year":"" ,"invitation_sent":false},
{"id":28, "name":"Gitumoni Borah", "subject":"", "phone": "","location":"","service_year":"" ,"invitation_sent":false},
{"id":29, "name":"Hariraj Singh", "subject":"Physics", "phone": "","location":"","service_year":"" ,"invitation_sent":false},
{"id":30, "name":"Illai Yadav", "subject":"Physics", "phone": "","location":"","service_year":"" ,"invitation_sent":false},
{"id":31, "name":"J P Yadav", "subject":"Hindi", "phone": "","location":"","service_year":"" ,"invitation_sent":false},
{"id":32, "name":"Jaya Bhadra", "subject":"Music", "phone": "","location":"","service_year":"" ,"invitation_sent":false},
{"id":33, "name":"Jitendra Kumar", "subject":"Art", "phone": "7978963036","location":"Bhubaneswar,Odisha","service_year":"" ,"invitation_sent":false},
{"id":34, "name":"Jitendra Sharma", "subject":"English", "phone": "","location":"","service_year":"" ,"invitation_sent":false},
{"id":35, "name":"Kabita Saikia", "subject":"Assamese", "phone": "","location":"JNV Rangiya","service_year":"" ,"invitation_sent":false},
{"id":36, "name":"KAKATI", "subject":"ASSAMESE", "phone": "","location":"","service_year":"" ,"invitation_sent":false},
{"id":37, "name":"Kamal Thakuriya", "subject":"UDC", "phone": "","location":"","service_year":"" ,"invitation_sent":false},
{"id":38, "name":"Kamala Bharadwaj", "subject":"Hindi", "phone": "","location":"","service_year":"" ,"invitation_sent":false},
{"id":39, "name":"Kamleshwar Barman", "subject":"English", "phone": "","location":"","service_year":"" ,"invitation_sent":false},
{"id":40, "name":"Karan Doley", "subject":"Maths", "phone": "","location":"","service_year":"" ,"invitation_sent":false},
{"id":41, "name":"Kataria Sir", "subject":"Hindi", "phone": "","location":"","service_year":"" ,"invitation_sent":false},
{"id":42, "name":"Khairul Zalal", "subject":"English", "phone": "","location":"JNV chirang","service_year":"" ,"invitation_sent":false},
{"id":43, "name":"Krishna Biswas", "subject":"Art", "phone": "","location":"","service_year":"" ,"invitation_sent":false},
{"id":44, "name":"Kulbir Bhujel ", "subject":"Biology", "phone": "","location":"","service_year":"" ,"invitation_sent":false},
{"id":45, "name":"Lal Bahadur Sharma", "subject":"Physics", "phone": "","location":"","service_year":"" ,"invitation_sent":false},
{"id":46, "name":"Late Sailendra Tripathi", "subject":"English", "phone": "","location":"","service_year":"" ,"invitation_sent":false},
{"id":47, "name":"Local Singh", "subject":"Maths", "phone": "","location":"","service_year":"" ,"invitation_sent":false},
{"id":48, "name":"M B Chetry", "subject":"GEOGRAPHY", "phone": "","location":"","service_year":"" ,"invitation_sent":false},
{"id":49, "name":"Madhumita", "subject":"Biology", "phone": "","location":"","service_year":"" ,"invitation_sent":false},
{"id":50, "name":"Madhumita Roy", "subject":"Music", "phone": "8638458901","location":"JNV Rangia","service_year":"" ,"invitation_sent":false},
{"id":51, "name":"Mahesh Chand", "subject":"Hindi", "phone": "9859069766","location":"JNV lalitpur, Uttar Pradesh ","service_year":"" ,"invitation_sent":false},
{"id":52, "name":"Manbahadur Chetri", "subject":"PET", "phone": "","location":"","service_year":"" ,"invitation_sent":false},
{"id":53, "name":"Mangalaima Devi", "subject":"English", "phone": "","location":"","service_year":"" ,"invitation_sent":false},
{"id":54, "name":"Manju Roy", "subject":"Music", "phone": "","location":"","service_year":"" ,"invitation_sent":false},
{"id":55, "name":"Manoj Deka", "subject":"Art", "phone": "","location":"","service_year":"" ,"invitation_sent":false},
{"id":56, "name":"Marami Maam", "subject":"PET", "phone": "","location":"","service_year":"" ,"invitation_sent":false},
{"id":57, "name":"Marry Thomas", "subject":"Maths", "phone": "8547561808","location":"","service_year":"" ,"invitation_sent":false},
{"id":58, "name":"Meenarva Maam", "subject":"Assamese", "phone": "","location":"","service_year":"" ,"invitation_sent":false},
{"id":59, "name":"Mendali Sir", "subject":"English", "phone": "","location":"","service_year":"" ,"invitation_sent":false},
{"id":60, "name":"Milan Kanti Sarkar", "subject":"Chemistry", "phone": "","location":"","service_year":"" ,"invitation_sent":false},
{"id":61, "name":"Minarva Goswami", "subject":"Assamese", "phone": "","location":"","service_year":"" ,"invitation_sent":false},
{"id":62, "name":"Minati Maam", "subject":"Nurse", "phone": "","location":"","service_year":"" ,"invitation_sent":false},
{"id":63, "name":"MK Roy", "subject":"History", "phone": "9365481911","location":"JNV Baksa","service_year":"" ,"invitation_sent":false},
{"id":64, "name":"Modan Mohan Mongal", "subject":"English", "phone": "","location":"","service_year":"" ,"invitation_sent":false},
{"id":65, "name":"Mohnani Sir", "subject":"Maths", "phone": "","location":"","service_year":"" ,"invitation_sent":false},
{"id":66, "name":"MP Singh", "subject":"Principal", "phone": "7014665940","location":"","service_year":"" ,"invitation_sent":false},
{"id":67, "name":"Mridula Chutiya", "subject":"History", "phone": "","location":"JNV Baithalangshoo ","service_year":"" ,"invitation_sent":false},
{"id":68, "name":"N.Dewan", "subject":"Computer", "phone": "9435758794","location":"Secretariat GHY","service_year":"" ,"invitation_sent":false},
{"id":69, "name":"Nasir Dewan", "subject":"Computer", "phone": "","location":"","service_year":"" ,"invitation_sent":false},
{"id":70, "name":"Niranjan Sharma", "subject":"Geography", "phone": "","location":"","service_year":"" ,"invitation_sent":false},
{"id":71, "name":"Noren singh", "subject":"PET", "phone": "","location":"","service_year":"" ,"invitation_sent":false},
{"id":72, "name":"P J Rao", "subject":"Physics", "phone": "","location":"","service_year":"" ,"invitation_sent":false},
{"id":73, "name":"P K Sarma ", "subject":"VP", "phone": "","location":"NCR, Delhi ","service_year":"" ,"invitation_sent":false},
{"id":74, "name":"P Pawar", "subject":"English", "phone": "9284168804","location":"jnv ahmednagar, Maharashtra ","service_year":"" ,"invitation_sent":false},
{"id":75, "name":"Parikshit Baishya", "subject":"Assamese", "phone": "","location":"","service_year":"" ,"invitation_sent":false},
{"id":76, "name":"Pallab Deka", "subject":"Assamese ", "phone": "","location":"Guwahati ","service_year":"" ,"invitation_sent":false},
{"id":77, "name":"Parthivan Sir", "subject":"Biology", "phone": "","location":"","service_year":"" ,"invitation_sent":false},
{"id":78, "name":"Patowary Sir", "subject":"Computer", "phone": "","location":"","service_year":"" ,"invitation_sent":false},
{"id":79, "name":"Pragati Sharma", "subject":"Assamese", "phone": "","location":"JNV Haflong ","service_year":"" ,"invitation_sent":false},
{"id":80, "name":"Pranjit Sharma", "subject":"English", "phone": "8474084820","location":"Assam","service_year":"" ,"invitation_sent":false},
{"id":81, "name":"Prasanna Deka", "subject":"Geography", "phone": "","location":"","service_year":"" ,"invitation_sent":false},
{"id":82, "name":"Prem Basfore", "subject":"Cleaner", "phone": "","location":"","service_year":"" ,"invitation_sent":false},
{"id":83, "name":"Promod Singh", "subject":"Hindi", "phone": "","location":"","service_year":"" ,"invitation_sent":false},
{"id":84, "name":"R Danial", "subject":"Principal", "phone": "","location":"","service_year":"" ,"invitation_sent":false},
{"id":85, "name":"Rajesh Bhowmik", "subject":"HM", "phone": "","location":"Tripura ","service_year":"" ,"invitation_sent":false},
{"id":86, "name":"Rajib Das", "subject":"Biology", "phone": "8093416213","location":"Assam","service_year":"" ,"invitation_sent":false},
{"id":87, "name":"Rajita Kalita", "subject":"Assamese", "phone": "","location":"","service_year":"" ,"invitation_sent":false},
{"id":88, "name":"Rakesh Kumar", "subject":"English", "phone": "","location":"","service_year":"" ,"invitation_sent":false},
{"id":89, "name":"Ramahari Sial", "subject":"Maths", "phone": "9678090491","location":"JNV kendrapara, Orissa ","service_year":"" ,"invitation_sent":false},
{"id":90, "name":"Ravish Kumar Pandey", "subject":"Library", "phone": "","location":"","service_year":"" ,"invitation_sent":false},
{"id":91, "name":"Rekha Shah", "subject":"Nurse", "phone": "","location":"","service_year":"" ,"invitation_sent":false},
{"id":92, "name":"Renu Sarkar", "subject":"Art", "phone": "","location":"","service_year":"" ,"invitation_sent":false},
{"id":93, "name":"RS Kani ", "subject":"Science", "phone": "","location":"","service_year":"" ,"invitation_sent":false},
{"id":94, "name":"Rumi Bhuyan", "subject":"English", "phone": "","location":"","service_year":"" ,"invitation_sent":false},
{"id":95, "name":"Rupali Maam", "subject":"Nurse", "phone": "","location":"","service_year":"" ,"invitation_sent":false},
{"id":96, "name":"S G Gawai", "subject":"Principal ", "phone": "","location":"JNV Amaravati, Maharashtra ","service_year":"" ,"invitation_sent":false},
{"id":97, "name":"S P Mukherjee", "subject":"Maths", "phone": "9830076638","location":"JNV Medinapore, WB","service_year":"" ,"invitation_sent":false},
{"id":98, "name":"S.T. Ali", "subject":"VP", "phone": "","location":"","service_year":"" ,"invitation_sent":false},
{"id":99, "name":"Sanjeev Bailung", "subject":"Assamese", "phone": "","location":"","service_year":"" ,"invitation_sent":false},
{"id":100, "name":"Santosh Bahuguna", "subject":"Maths", "phone": "6397905906","location":"","service_year":"" ,"invitation_sent":false},
{"id":101, "name":"Santosh Bora ", "subject":"Catering ", "phone": "","location":"Jnv Golaghat ","service_year":"" ,"invitation_sent":false},
{"id":102, "name":"Sashi Sir", "subject":"Chemistry", "phone": "","location":"","service_year":"" ,"invitation_sent":false},
{"id":103, "name":"Sharma Khura", "subject":"Mess", "phone": "","location":"","service_year":"" ,"invitation_sent":false},
{"id":104, "name":"Stela Kurba", "subject":"Library", "phone": "","location":"","service_year":"" ,"invitation_sent":false},
{"id":105, "name":"Subrata Majumder", "subject":"", "phone": "","location":"","service_year":"" ,"invitation_sent":false},
{"id":106, "name":"Sunny Joseph", "subject":"Maths", "phone": "9449997105","location":"","service_year":"" ,"invitation_sent":false},
{"id":107, "name":"Sushil Patowary", "subject":"Computer", "phone": "7002118673","location":"Assam","service_year":"" ,"invitation_sent":false},
{"id":108, "name":"T N Thangjam", "subject":"Chemistry", "phone": "","location":"","service_year":"" ,"invitation_sent":false},
{"id":109, "name":"Talukdar Khura", "subject":"Mess", "phone": "","location":"","service_year":"" ,"invitation_sent":false},
{"id":110, "name":"Tangavelu", "subject":"Principal", "phone": "","location":"","service_year":"" ,"invitation_sent":false},
{"id":111, "name":"Tapashi Mazumder", "subject":"Science", "phone": "","location":"","service_year":"" ,"invitation_sent":false},
{"id":112, "name":"Upendra Yadav ", "subject":"Maths", "phone": "","location":"","service_year":"" ,"invitation_sent":false},
{"id":113, "name":"Vijay Nathani", "subject":"Maths", "phone": "","location":"","service_year":"" ,"invitation_sent":false},
{"id":114, "name":"Y Santa", "subject":"PET", "phone": "","location":"","service_year":"" ,"invitation_sent":false},
{"id":115, "name":"Yaar Ali ", "subject":"SST", "phone": "","location":"","service_year":"" ,"invitation_sent":false},
]