export const galleryImages = [{"id":1, "desc":"1998-1999", "src": "1.jpeg", "caption": "Batch:1998-1999 - Before the Annual day - (Deamon Egg)","thumb":""},
{"id":2, "desc":"1998-1999", "src": "2.jpeg", "caption": "Batch:1998-1999 - Class room - (10th Standard)", "thumb":""},
{"id":3, "desc":"1998-1999", "src": "3.jpeg", "caption": "Batch:1998-1999 - Group photo with Giridhar Sir", "thumb":""},
{"id":4, "desc":"Others", "src": "2.JPG", "caption": "Photo with T.N. Singh Sir", "thumb":""},
{"id":5, "desc":"Others", "src": "3.JPG", "caption": "Bathing time - Pose by Lal Bahadur Sir", "thumb":""},
{"id":6, "desc":"Others", "src": "5.JPG", "caption": "Annual sports day", "thumb":""},
{"id":7, "desc":"Others", "src": "16.JPG", "caption": "A Scene from a not so famous drama - Daemon Egg - Annual Day", "thumb":""},
{"id":8, "desc":"1997-1998", "src": "22.JPG", "caption": "Batch:1997-1998 - Attending class", "thumb":""},
{"id":9, "desc":"Old Campus", "src": "1 (1).jpg", "caption": "Old Campus","thumb":""},
{"id":10, "desc":"Old Campus", "src": "1 (2).jpg", "caption": "Old Campus","thumb":""},
{"id":11, "desc":"Old Campus", "src": "1 (3).jpg", "caption": "Old Campus","thumb":""},
{"id":12, "desc":"Old Campus", "src": "1 (4).jpg", "caption": "Old Campus","thumb":""},
{"id":13, "desc":"Old Campus", "src": "1 (5).jpg", "caption": "Old Campus","thumb":""},
{"id":14, "desc":"Old Campus", "src": "1 (6).jpg", "caption": "Old Campus","thumb":""},
{"id":15, "desc":"Old Campus", "src": "1 (7).jpg", "caption": "Old Campus","thumb":""},
{"id":16, "desc":"Old Campus", "src": "1 (8).jpg", "caption": "Old Campus","thumb":""},
{"id":17, "desc":"Old Campus", "src": "1 (9).jpg", "caption": "Old Campus","thumb":""},
{"id":18, "desc":"Old Campus", "src": "1 (10).jpg", "caption": "Old Campus","thumb":""},
{"id":19, "desc":"Old Campus", "src": "1 (11).jpg", "caption": "Old Campus","thumb":""},
{"id":20, "desc":"Old Campus", "src": "1 (12).jpg", "caption": "Old Campus","thumb":""},
{"id":21, "desc":"Old Campus", "src": "1 (13).jpg", "caption": "Old Campus","thumb":""},
{"id":22, "desc":"Old Campus", "src": "1.JPG", "caption": "Old Campus","thumb":""},
{"id":23, "desc":"Old Campus", "src": "2.JPG", "caption": "Old Campus","thumb":""},
{"id":24, "desc":"Old Campus", "src": "3.JPG", "caption": "Old Campus","thumb":""},
{"id":25, "desc":"Old Campus", "src": "4.JPG", "caption": "Old Campus","thumb":""},
{"id":26, "desc":"Old Campus", "src": "5.JPG", "caption": "Old Campus","thumb":""},
{"id":27, "desc":"Old Campus", "src": "6.JPG", "caption": "Old Campus","thumb":""},
{"id":28, "desc":"Old Campus", "src": "7.JPG", "caption": "Old Campus","thumb":""},
{"id":29, "desc":"Old Campus", "src": "8.JPG", "caption": "Old Campus","thumb":""},
{"id":30, "desc":"Old Campus", "src": "9.JPG", "caption": "Old Campus","thumb":""},
{"id":31, "desc":"Old Campus", "src": "10.JPG", "caption": "Old Campus","thumb":""},
{"id":32, "desc":"Old Campus", "src": "11.JPG", "caption": "Old Campus","thumb":""},
{"id":33, "desc":"Old Campus", "src": "12.JPG", "caption": "Old Campus","thumb":""},
{"id":34, "desc":"1998-1999", "src": "1 (1).jpg", "caption": "1998-1999","thumb":""},
{"id":35, "desc":"1998-1999", "src": "1 (2).jpg", "caption": "1998-1999","thumb":""},
{"id":36, "desc":"1998-1999", "src": "1 (3).jpg", "caption": "1998-1999","thumb":""},
{"id":37, "desc":"1998-1999", "src": "4.JPG", "caption": "1998-1999","thumb":""},
{"id":38, "desc":"1998-1999", "src": "1 (5).JPG", "caption": "1998-1999","thumb":""},
{"id":39, "desc":"1998-1999", "src": "1 (6).JPG", "caption": "1998-1999","thumb":""},
{"id":40, "desc":"1998-1999", "src": "1 (7).JPG", "caption": "1998-1999","thumb":""},
{"id":41, "desc":"1998-1999", "src": "1 (8).JPG", "caption": "1998-1999","thumb":""},
{"id":42, "desc":"1998-1999", "src": "1 (9).JPG", "caption": "1998-1999","thumb":""},
{"id":43, "desc":"1998-1999", "src": "1 (10).jpg", "caption": "1998-1999","thumb":""},
{"id":44, "desc":"1998-1999", "src": "1 (11).jpg", "caption": "1998-1999","thumb":""},
{"id":45, "desc":"1998-1999", "src": "1 (12).JPG", "caption": "1998-1999","thumb":""},
{"id":46, "desc":"Others", "src": "1 (1).JPG", "caption": "Others","thumb":""},
{"id":47, "desc":"Others", "src": "1 (2).JPG", "caption": "Others","thumb":""},
{"id":48, "desc":"Others", "src": "1 (3).JPG", "caption": "Others","thumb":""},
{"id":49, "desc":"Others", "src": "1 (4).JPG", "caption": "Others","thumb":""},
{"id":50, "desc":"Others", "src": "1 (5).JPG", "caption": "Others","thumb":""},
{"id":51, "desc":"Others", "src": "1 (6).JPG", "caption": "Others","thumb":""},
{"id":52, "desc":"Others", "src": "1 (7).JPG", "caption": "Others","thumb":""},
{"id":53, "desc":"Others", "src": "1 (8).JPG", "caption": "Others","thumb":""},
{"id":54, "desc":"Others", "src": "1 (9).JPG", "caption": "Others","thumb":""},
{"id":55, "desc":"Others", "src": "1 (10).JPG", "caption": "Others","thumb":""},
{"id":56, "desc":"Others", "src": "1 (11).JPG", "caption": "Others","thumb":""},
{"id":57, "desc":"Others", "src": "1 (12).JPG", "caption": "Others","thumb":""},
{"id":58, "desc":"Others", "src": "1 (13).JPG", "caption": "Others","thumb":""},
{"id":59, "desc":"Others", "src": "1 (14).JPG", "caption": "Others","thumb":""},
{"id":60, "desc":"Others", "src": "1 (15).JPG", "caption": "Others","thumb":""},
{"id":61, "desc":"Others", "src": "1 (16).JPG", "caption": "Others","thumb":""},
{"id":62, "desc":"Others", "src": "1 (17).jpg", "caption": "Others","thumb":""},
{"id":63, "desc":"Others", "src": "1 (18).jpg", "caption": "Others","thumb":""},
{"id":64, "desc":"Others", "src": "1 (19).jpg", "caption": "Others","thumb":""},
{"id":65, "desc":"1995-1996", "src": "1 (1).jpg", "caption": "1995-1996","thumb":""},
{"id":66, "desc":"1995-1996", "src": "1 (2).jpg", "caption": "1995-1996","thumb":""},
{"id":67, "desc":"1995-1996", "src": "1 (3).jpg", "caption": "1995-1996","thumb":""},
{"id":68, "desc":"Others", "src": "2 (1).jpg", "caption": "Others","thumb":""},
{"id":69, "desc":"Others", "src": "2 (2).jpg", "caption": "Others","thumb":""},
{"id":70, "desc":"Others", "src": "2 (3).jpg", "caption": "Others","thumb":""},
{"id":71, "desc":"Others", "src": "2 (4).jpg", "caption": "Others","thumb":""},
{"id":72, "desc":"Others", "src": "2 (5).jpg", "caption": "Others","thumb":""},
{"id":73, "desc":"Others", "src": "2 (6).jpg", "caption": "Others","thumb":""},
{"id":74, "desc":"Others", "src": "2 (7).jpg", "caption": "Others","thumb":""},
{"id":75, "desc":"Others", "src": "3 (1).jpg", "caption": "Others","thumb":""},
{"id":76, "desc":"Others", "src": "3 (2).jpg", "caption": "Others","thumb":""},
{"id":77, "desc":"Others", "src": "3 (3).jpg", "caption": "Others","thumb":""},
{"id":78, "desc":"Others", "src": "3 (4).jpg", "caption": "Others","thumb":""},
{"id":79, "desc":"Others", "src": "3 (5).jpg", "caption": "Others","thumb":""},
{"id":80, "desc":"Others", "src": "3 (6).jpg", "caption": "Others","thumb":""},
{"id":81, "desc":"Others", "src": "3 (7).jpg", "caption": "Others","thumb":""},
{"id":82, "desc":"Health Camp", "src": "1 (1).jpg", "caption": "Health Camp","thumb":""},
{"id":83, "desc":"Health Camp", "src": "1 (2).jpg", "caption": "Health Camp","thumb":""},
{"id":84, "desc":"Health Camp", "src": "1 (3).jpg", "caption": "Health Camp","thumb":""},
{"id":85, "desc":"Plantation Drive", "src": "1 (1).jpg", "caption": "Plantation Drive","thumb":""},
{"id":86, "desc":"Plantation Drive", "src": "1 (2).jpg", "caption": "Plantation Drive","thumb":""},
{"id":87, "desc":"Jyotisman Award", "src": "1 (1).jpeg", "caption": "A jyotisman award is being given to every class topper JNV Nalbari from class vi to xi in the name of late Arup kr.Baishya.It was started from 2022.","thumb":""},
{"id":88, "desc":"Jyotisman Award", "src": "1 (2).jpeg", "caption": "A jyotisman award is being given to every class topper JNV Nalbari from class vi to xi in the name of late Arup kr.Baishya.It was started from 2022.","thumb":""},
{"id":89, "desc":"Jyotisman Award", "src": "1 (3).jpeg", "caption": "A jyotisman award is being given to every class topper JNV Nalbari from class vi to xi in the name of late Arup kr.Baishya.It was started from 2022.","thumb":""},
{"id":90, "desc":"Jyotisman Award", "src": "1 (4).jpeg", "caption": "A jyotisman award is being given to every class topper JNV Nalbari from class vi to xi in the name of late Arup kr.Baishya.It was started from 2022.","thumb":""},
{"id":91, "desc":"2002-2003", "src": "1 (1).jpeg", "caption": "2002-2003","thumb":""},
{"id":92, "desc":"2002-2003", "src": "1 (2).jpeg", "caption": "2002-2003","thumb":""},
{"id":93, "desc":"2002-2003", "src": "1 (3).jpeg", "caption": "15 august 2003","thumb":""},
{"id":94, "desc":"Others", "src": "4 (1).jpeg", "caption": "New year picnic day at banekuchi.. Teachers","thumb":""},
{"id":95, "desc":"Others", "src": "4 (2).jpeg", "caption": "Manju Kumari Roy madam","thumb":""},
{"id":96, "desc":"Others", "src": "4 (3).jpeg", "caption": "Nilgiri girls hostel","thumb":""},
{"id":97, "desc":"Others", "src": "4 (4).jpeg", "caption": "Others","thumb":""},
{"id":98, "desc":"1996-1997", "src": "1.jpeg", "caption": "1996-1997","thumb":""},


]